/* variants */

const EN = "en";
const ENGLISH = "English";

const FR = "fr";
const FRANÇAIS = "français";

/* data */

const enData = Object.freeze({
  tsDoc: Object.freeze({
    src: Object.freeze({
      consts: Object.freeze({
        messages: Object.freeze({
          absolutePathIsSupposedToBeAString:
            "`absolutePath` is supposed to be a string." /* variations: $COMMENT#TSDOC#SRC#CONSTS#MESSAGES#ABSOLUTEPATHISSUPPOSEDTOBEASTRING / core: $COMMENT#EN#TSDOC#SRC#CONSTS#MESSAGES#ABSOLUTEPATHISSUPPOSEDTOBEASTRING */,
          absolutePathCouldntBeRead:
            "Absolute file path could not be read." /* variations: $COMMENT#TSDOC#SRC#CONSTS#MESSAGES#ABSOLUTEPATHCOULDNTBEREAD / core: $COMMENT#EN#TSDOC#SRC#CONSTS#MESSAGES#ABSOLUTEPATHCOULDNTBEREAD */,
          jsTsJsxTsxCouldntBeParsed:
            "JS/TS/JSX/TSX source code could not be parsed." /* variations: $COMMENT#TSDOC#SRC#CONSTS#MESSAGES#JSTSJSXTSXCOULDNTBEPARSED / core: $COMMENT#EN#TSDOC#SRC#CONSTS#MESSAGES#JSTSJSXTSXCOULDNTBEPARSED */,
        }),
        statuses: Object.freeze({
          public: Object.freeze({
            ABSOLUTE_PATH_NOT_STRING:
              '"$COMMENT#EN#TSDOC#SRC#CONSTS#MESSAGES#ABSOLUTEPATHISSUPPOSEDTOBEASTRING"' /* variations: $COMMENT#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#ABSOLUTE_PATH_NOT_STRING / core: $COMMENT#EN#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#ABSOLUTE_PATH_NOT_STRING */,
            ABSOLUTE_PATH_NOT_FOUND:
              '"$COMMENT#EN#TSDOC#SRC#CONSTS#MESSAGES#ABSOLUTEPATHCOULDNTBEREAD"' /* variations: $COMMENT#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#ABSOLUTE_PATH_NOT_FOUND / core: $COMMENT#EN#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#ABSOLUTE_PATH_NOT_FOUND */,
            SOURCE_CODE_FATAL_SYNTAX:
              '"$COMMENT#EN#TSDOC#SRC#CONSTS#MESSAGES#JSTSJSXTSXCOULDNTBEPARSED"' /* variations: $COMMENT#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#SOURCE_CODE_FATAL_SYNTAX / core: $COMMENT#EN#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#SOURCE_CODE_FATAL_SYNTAX */,
          }),
        }),
      }),
      lib: Object.freeze({
        consts: Object.freeze({
          public: Object.freeze({
            successFalse:
              "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSFALSE` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSFALSE}`." /* variations: $COMMENT#TSDOC#SRC#LIB#CONSTS#PUBLIC#SUCCESSFALSE / core: $COMMENT#EN#TSDOC#SRC#LIB#CONSTS#PUBLIC#SUCCESSFALSE */,
            successTrue:
              "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSTRUE` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_TRUE` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSTRUE}`." /* variations: $COMMENT#TSDOC#SRC#LIB#CONSTS#PUBLIC#SUCCESSTRUE / core: $COMMENT#EN#TSDOC#SRC#LIB#CONSTS#PUBLIC#SUCCESSTRUE */,
            typeError:
              "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEERROR` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEERROR}`." /* variations: $COMMENT#TSDOC#SRC#LIB#CONSTS#PUBLIC#TYPEERROR / core: $COMMENT#EN#TSDOC#SRC#LIB#CONSTS#PUBLIC#TYPEERROR */,
            typeWarning:
              "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEWARNING` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEWARNING}`." /* variations: $COMMENT#TSDOC#SRC#LIB#CONSTS#PUBLIC#TYPEWARNING / core: $COMMENT#EN#TSDOC#SRC#LIB#CONSTS#PUBLIC#TYPEWARNING */,
          }),
          parser: Object.freeze({
            public: Object.freeze({
              typeScriptAndJSXCompatible:
                "`languageOptions` object for instances of the `ESLint` and `Linter` classes enabling the linting of TypeScript and JSX (React) files." /* variations: $COMMENT#TSDOC#SRC#LIB#CONSTS#PARSER#PUBLIC#TYPESCRIPTANDJSXCOMPATIBLE / core: $COMMENT#EN#TSDOC#SRC#LIB#CONSTS#PARSER#PUBLIC#TYPESCRIPTANDJSXCOMPATIBLE */,
            }),
          }),
        }),
        defs: Object.freeze({
          public: Object.freeze({
            getSourceCode:
              "Gets the $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE from its absolute path." /* variations: $COMMENT#TSDOC#SRC#LIB#DEFS#PUBLIC#GETSOURCECODE / core: $COMMENT#EN#TSDOC#SRC#LIB#DEFS#PUBLIC#GETSOURCECODE */,
          }),
          utils: Object.freeze({
            public: Object.freeze({
              makeSuccessFalseTypeError:
                "Makes a `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` object with a $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR of `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR}` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS." /* variations: $COMMENT#TSDOC#SRC#LIB#DEFS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEERROR / core: $COMMENT#EN#TSDOC#SRC#LIB#DEFS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEERROR */,
              makeSuccessFalseTypeWarning:
                "Makes a `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` object with a $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR of `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING}` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS." /* variations: $COMMENT#TSDOC#SRC#LIB#DEFS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEWARNING / core: $COMMENT#EN#TSDOC#SRC#LIB#DEFS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEWARNING */,
            }),
          }),
        }),
        params: Object.freeze({
          public: Object.freeze({
            absolutePath:
              "The $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ABSOLUTEPATH $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ATHAND." /* variations: $COMMENT#TSDOC#SRC#LIB#PARAMS#PUBLIC#ABSOLUTEPATH / core: $COMMENT#EN#TSDOC#SRC#LIB#PARAMS#PUBLIC#ABSOLUTEPATH */,
          }),
          utils: Object.freeze({
            public: Object.freeze({
              message:
                "The human-readable message of the $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ERROR." /* variations: $COMMENT#TSDOC#SRC#LIB#PARAMS#UTILS#PUBLIC#MESSAGE / core: $COMMENT#EN#TSDOC#SRC#LIB#PARAMS#UTILS#PUBLIC#MESSAGE */,
              status:
                "The static status text of the $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ERROR." /* variations: $COMMENT#TSDOC#SRC#LIB#PARAMS#UTILS#PUBLIC#STATUS / core: $COMMENT#EN#TSDOC#SRC#LIB#PARAMS#UTILS#PUBLIC#STATUS */,
            }),
          }),
        }),
        returns: Object.freeze({
          public: Object.freeze({
            getSourceCode:
              "The $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE, from which the AST (`sourceCode.ast`) and all comments (`sourceCode.getAllComments()`) can be extracted, inside a `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_TRUE}` object at its `sourceCode` key. In case of an error, a `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` object is returned instead." /* variations: $COMMENT#TSDOC#SRC#LIB#RETURNS#PUBLIC#GETSOURCECODE / core: $COMMENT#EN#TSDOC#SRC#LIB#RETURNS#PUBLIC#GETSOURCECODE */,
          }),
          utils: Object.freeze({
            public: Object.freeze({
              makeSuccessFalseTypeError:
                "A `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` object with a $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR of `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR}`." /* variations: $COMMENT#TSDOC#SRC#LIB#RETURNS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEERROR / core: $COMMENT#EN#TSDOC#SRC#LIB#RETURNS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEERROR */,
              makeSuccessFalseTypeWarning:
                "A `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` object with a $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR of `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING}`." /* variations: $COMMENT#TSDOC#SRC#LIB#RETURNS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEWARNING / core: $COMMENT#EN#TSDOC#SRC#LIB#RETURNS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEWARNING */,
            }),
          }),
        }),
      }),
      tests: Object.freeze({
        defs: Object.freeze({
          utils: Object.freeze({
            assertFailureWithMessage:
              "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_ASSERTS that `$COMMENT#EN#FORCOMPOSEDVARIABLES#GETSOURCECODE` fails $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#WHENITSHOULD." /* variations: $COMMENT#TSDOC#SRC#TESTS#DEFS#UTILS#ASSERTFAILUREWITHMESSAGE / core: $COMMENT#EN#TSDOC#SRC#TESTS#DEFS#UTILS#ASSERTFAILUREWITHMESSAGE */,
            assertSuccess:
              "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_ASSERTS that `$COMMENT#EN#FORCOMPOSEDVARIABLES#GETSOURCECODE` succeeds $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#WHENITSHOULD." /* variations: $COMMENT#TSDOC#SRC#TESTS#DEFS#UTILS#ASSERTSUCCESS / core: $COMMENT#EN#TSDOC#SRC#TESTS#DEFS#UTILS#ASSERTSUCCESS */,
          }),
        }),
        params: Object.freeze({
          utils: Object.freeze({
            getSourceCodeResults:
              "The results of the `$COMMENT#EN#FORCOMPOSEDVARIABLES#GETSOURCECODE` instance called in the test, whose success or failure is evaluated via its `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS` key's boolean value." /* variations: $COMMENT#TSDOC#SRC#TESTS#PARAMS#UTILS#GETSOURCECODERESULTS / core: $COMMENT#EN#TSDOC#SRC#TESTS#PARAMS#UTILS#GETSOURCECODERESULTS */,
            expectedMessage:
              "The expected $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#MESSAGE of the error that should be encountered during failure, from which the $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#STATUS can be inferred." /* variations: $COMMENT#TSDOC#SRC#TESTS#PARAMS#UTILS#EXPECTEDMESSAGE / core: $COMMENT#EN#TSDOC#SRC#TESTS#PARAMS#UTILS#EXPECTEDMESSAGE */,
          }),
        }),
        returns: Object.freeze({
          utils: Object.freeze({
            assertFailureWithMessage:
              "Void." /* variations: $COMMENT#TSDOC#SRC#TESTS#RETURNS#UTILS#ASSERTFAILUREWITHMESSAGE / core: $COMMENT#EN#TSDOC#SRC#TESTS#RETURNS#UTILS#ASSERTFAILUREWITHMESSAGE */,
            assertSuccess:
              "EN#TSDOC#SRC#TESTS#RETURNS#UTILS#ASSERTFAILUREWITHMESSAGE" /* variations: $COMMENT#TSDOC#SRC#TESTS#RETURNS#UTILS#ASSERTSUCCESS / core: $COMMENT#EN#TSDOC#SRC#TESTS#RETURNS#UTILS#ASSERTSUCCESS */,
          }),
        }),
      }),
    }),
  }),
  forComposedVariables: Object.freeze({
    // tsDoc.tests.defs
    getSourceCode:
      "getSourceCode" /* variations: $COMMENT#FORCOMPOSEDVARIABLES#GETSOURCECODE / core: $COMMENT#EN#FORCOMPOSEDVARIABLES#GETSOURCECODE */,
  }),
  composedVariablesExclusives: Object.freeze({
    // tsDoc.core.consts
    successFalse:
      "successFalse" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSFALSE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSFALSE */,
    successTrue:
      "successTrue" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSTRUE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSTRUE */,
    typeError:
      "typeError" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TYPEERROR / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEERROR */,
    typeWarning:
      "typeWarning" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TYPEWARNING / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEWARNING */,
    success_false:
      "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#FALSE" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE */,
    success_true:
      "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TRUE" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_TRUE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_TRUE */,
    type_error:
      "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ERROR" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR */,
    type_warning:
      "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#WARNING" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING */,
    success:
      "success" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS */,
    false:
      "false" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#FALSE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#FALSE */,
    true: "true" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TRUE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TRUE */,
    type: "type" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TYPE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE */,
    error:
      "error" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#ERROR / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ERROR */,
    warning:
      "warning" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#WARNING / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#WARNING */,
    _applyLastWith:
      "Apply last with" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH */,
    toEnsure:
      "to ensure that" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE */,
    sitsAtTopLike:
      "sits at the top of its object's type definition, like" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE */,
    propApropB:
      "propertyA, propertyB" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB */,
    // tsDoc.core.defs
    eslintSourceCode:
      "ESLint-generated `SourceCode` object of a file" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE */,
    singleError:
      "single error in its `errors` array" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR */,
    basedOnMessageAndStatus:
      "based on the `message` it is meant to display and the `status` it is meant to have" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS */,
    // tsDoc.core.params
    absolutePath:
      "absolute path of the file" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#ABSOLUTEPATH / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ABSOLUTEPATH */,
    atHand:
      "at hand" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#ATHAND / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ATHAND */,
    // tsDoc.tests.defs
    _asserts:
      "Asserts" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#_ASSERTS / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_ASSERTS */,
    whenItShould:
      "when it should" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#WHENITSHOULD / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#WHENITSHOULD */,
    // tsDoc.tests.params
    message:
      "message" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#MESSAGE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#MESSAGE */,
    status:
      "status" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#STATUS / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#STATUS */,
  }),
});

const frData = Object.freeze({
  tsDoc: Object.freeze({
    src: Object.freeze({
      consts: Object.freeze({
        statuses: Object.freeze({
          public: Object.freeze({
            ABSOLUTE_PATH_NOT_STRING:
              '$COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#_ENANGLAIS : "$COMMENT#EN#TSDOC#SRC#CONSTS#MESSAGES#ABSOLUTEPATHISSUPPOSEDTOBEASTRING"' /* variations: $COMMENT#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#ABSOLUTE_PATH_NOT_STRING / core: $COMMENT#FR#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#ABSOLUTE_PATH_NOT_STRING */,
            ABSOLUTE_PATH_NOT_FOUND:
              '$COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#_ENANGLAIS : "$COMMENT#EN#TSDOC#SRC#CONSTS#MESSAGES#ABSOLUTEPATHCOULDNTBEREAD"' /* variations: $COMMENT#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#ABSOLUTE_PATH_NOT_FOUND / core: $COMMENT#FR#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#ABSOLUTE_PATH_NOT_FOUND */,
            SOURCE_CODE_FATAL_SYNTAX:
              '$COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#_ENANGLAIS : "$COMMENT#EN#TSDOC#SRC#CONSTS#MESSAGES#JSTSJSXTSXCOULDNTBEPARSED"' /* variations: $COMMENT#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#SOURCE_CODE_FATAL_SYNTAX / core: $COMMENT#FR#TSDOC#SRC#CONSTS#STATUSES#PUBLIC#SOURCE_CODE_FATAL_SYNTAX */,
          }),
        }),
      }),
      lib: Object.freeze({
        consts: Object.freeze({
          public: Object.freeze({
            successFalse:
              "$COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSFALSE` $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE` $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSFALSE}`." /* variations: $COMMENT#TSDOC#SRC#LIB#CONSTS#PUBLIC#SUCCESSFALSE / core: $COMMENT#FR#TSDOC#SRC#LIB#CONSTS#PUBLIC#SUCCESSFALSE */,
            successTrue:
              "$COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSTRUE` $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_TRUE` $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSTRUE}`." /* variations: $COMMENT#TSDOC#SRC#LIB#CONSTS#PUBLIC#SUCCESSTRUE / core: $COMMENT#FR#TSDOC#SRC#LIB#CONSTS#PUBLIC#SUCCESSTRUE */,
            typeError:
              "$COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEERROR` $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR` $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEERROR}`." /* variations: $COMMENT#TSDOC#SRC#LIB#CONSTS#PUBLIC#TYPEERROR / core: $COMMENT#FR#TSDOC#SRC#LIB#CONSTS#PUBLIC#TYPEERROR */,
            typeWarning:
              "$COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEWARNING` $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING` $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEWARNING}`." /* variations: $COMMENT#TSDOC#SRC#LIB#CONSTS#PUBLIC#TYPEWARNING / core: $COMMENT#FR#TSDOC#SRC#LIB#CONSTS#PUBLIC#TYPEWARNING */,
          }),
          parser: Object.freeze({
            public: Object.freeze({
              typeScriptAndJSXCompatible:
                "Objet `languageOptions` pour instances de classes `ESLint` et `Linter` permettant l'analyse statique de fichiers TypeScript et JSX (React)." /* variations: $COMMENT#TSDOC#SRC#LIB#CONSTS#PARSER#PUBLIC#TYPESCRIPTANDJSXCOMPATIBLE / core: $COMMENT#FR#TSDOC#SRC#LIB#CONSTS#PARSER#PUBLIC#TYPESCRIPTANDJSXCOMPATIBLE */,
            }),
          }),
        }),
        defs: Object.freeze({
          public: Object.freeze({
            getSourceCode:
              "Obtient l'$COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE à partir de son chemin absolu." /* variations: $COMMENT#TSDOC#SRC#LIB#DEFS#PUBLIC#GETSOURCECODE / core: $COMMENT#FR#TSDOC#SRC#LIB#DEFS#PUBLIC#GETSOURCECODE */,
          }),
          utils: Object.freeze({
            public: Object.freeze({
              makeSuccessFalseTypeError:
                "Crée un objet `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` avec une $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR de `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR}` $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS." /* variations: $COMMENT#TSDOC#SRC#LIB#DEFS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEERROR / core: $COMMENT#FR#TSDOC#SRC#LIB#DEFS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEERROR */,
              makeSuccessFalseTypeWarning:
                "Crée un objet `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` avec une $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR de `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING}` $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS." /* variations: $COMMENT#TSDOC#SRC#LIB#DEFS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEWARNING / core: $COMMENT#FR#TSDOC#SRC#LIB#DEFS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEWARNING */,
            }),
          }),
        }),
        params: Object.freeze({
          public: Object.freeze({
            absolutePath:
              "Le $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#ABSOLUTEPATH $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#CONCERNÉ." /* variations: $COMMENT#TSDOC#SRC#LIB#PARAMS#PUBLIC#ABSOLUTEPATH / core: $COMMENT#FR#TSDOC#SRC#LIB#PARAMS#PUBLIC#ABSOLUTEPATH */,
          }),
          utils: Object.freeze({
            public: Object.freeze({
              message:
                "Le message en clair de l'$COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#ERROR." /* variations: $COMMENT#TSDOC#SRC#LIB#PARAMS#UTILS#PUBLIC#MESSAGE / core: $COMMENT#FR#TSDOC#SRC#LIB#PARAMS#UTILS#PUBLIC#MESSAGE */,
              status:
                "Le texte statique du statut de l'$COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#ERROR." /* variations: $COMMENT#TSDOC#SRC#LIB#PARAMS#UTILS#PUBLIC#STATUS / core: $COMMENT#FR#TSDOC#SRC#LIB#PARAMS#UTILS#PUBLIC#STATUS */,
            }),
          }),
        }),
        returns: Object.freeze({
          public: Object.freeze({
            getSourceCode:
              "L'$COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE, à partir duquel l'AST (`sourceCode.ast`) et tous les commentaires (`sourceCode.getAllComments()`) peuvent être extraits, à l'intérieur d'un objet `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_TRUE}` à sa clé `sourceCode`. En cas d'erreur, un objet `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` est retourné à la place." /* variations: $COMMENT#TSDOC#SRC#LIB#RETURNS#PUBLIC#GETSOURCECODE / core: $COMMENT#FR#TSDOC#SRC#LIB#RETURNS#PUBLIC#GETSOURCECODE */,
          }),
          utils: Object.freeze({
            public: Object.freeze({
              makeSuccessFalseTypeError:
                "Un objet `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` avec une $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR de `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR}`." /* variations: $COMMENT#TSDOC#SRC#LIB#RETURNS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEERROR / core: $COMMENT#FR#TSDOC#SRC#LIB#RETURNS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEERROR */,
              makeSuccessFalseTypeWarning:
                "Un objet `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` avec une $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR de `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING}`." /* variations: $COMMENT#TSDOC#SRC#LIB#RETURNS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEWARNING / core: $COMMENT#FR#TSDOC#SRC#LIB#RETURNS#UTILS#PUBLIC#MAKESUCCESSFALSETYPEWARNING */,
            }),
          }),
        }),
      }),
    }),
  }),
  forComposedVariables: Object.freeze({}),
  composedVariablesExclusives: Object.freeze({
    // tsDoc.source.consts
    _enAnglais:
      "En anglais à l'exécution" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#_ENANGLAIS / core: $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#_ENANGLAIS */,
    // tsDoc.core.consts
    error:
      "erreur" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#ERROR / core: $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#ERROR */,
    _applyLastWith:
      "À apposer en dernier via" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH / core: $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH */,
    toEnsure:
      "pour s'assurer que" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE / core: $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE */,
    sitsAtTopLike:
      "apparaisse au sommet de la définition du type de l'objet auquel il appartient, façon" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE / core: $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE */,
    // tsDoc.core.defs
    eslintSourceCode:
      "objet `SourceCode` généré par ESLint d'un fichier" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE / core: $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE */,
    singleError:
      "seule erreur dans son array `errors`" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR / core: $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR */,
    basedOnMessageAndStatus:
      "basée sur le `message` qu'elle doit montrer et le `status` qu'elle doit avoir" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS / core: $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS */,
    // tsDoc.core.params
    absolutePath:
      "chemin absolu du fichier" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#ABSOLUTEPATH / core: $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#ABSOLUTEPATH */,
    concerné:
      "concerné" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#CONCERNÉ / core: $COMMENT#FR#COMPOSEDVARIABLESEXCLUSIVES#CONCERNÉ */,
  }),
});

const data = Object.freeze({
  [EN]: enData,
  [FR]: frData,
});

/* ignores */

const ignores = [];

/* lintConfigImports */

const lintConfigImports = false; // can be omitted

/* myIgnoresOnly */

const myIgnoresOnly = false; // can be omitted

/* composedVariablesExclusives */

const enComposedVariablesExclusives = [];
const frComposedVariablesExclusives = [];

const composedVariablesExclusives = [
  ...enComposedVariablesExclusives,
  ...frComposedVariablesExclusives,
]; // composed variables allowed, Comment Variables that include `#COMPOSEDVARIABLESEXCLUSIVES#` are implicitly added

/* variations */

const variations = Object.freeze({
  // Defines all variants that have matching variations duly defined within the top-level keys of `data`.
  variants: Object.freeze({
    [EN]: Object.freeze({ label: ENGLISH }),
    [FR]: Object.freeze({ label: FRANÇAIS }),
  }),
  // Defines the current variant that Comment Variables currently resolves to.
  variant: FR,
  // Defines the reference variation that all other variations need to have (or aim to have) matching keys with. Requires a JavaScript variable as it needs to be the exact same object as the one referenced at `data[variations.referenceVariant]`.
  referenceData: enData,
  // Defines the variant of the reference variation.
  referenceVariant: EN,
  // Defines the behavior of the error handling in case of variations that do not match one-to-one with the reference variation. If `true`, allows incomplete variations data to remain. If `false`, errors and guides the fixing of missing variations data (while ignoring composed variables exclusives).
  allowIncompleteVariations: true,
  // Defines which variants' `#PUBLIC#` Comment Variables should be publicly available, by default through `comments.public.mjs` and `comments.public.json`.
  // public: [EN, FR] // v3
});

// /* libraries */

// import { commentVariablesData as libraryCommentVariablesData } from "library"

// const libraries = {
//   "library": libraryCommentVariablesData.variantKey
// } // v3

const config = {
  data,
  ignores,
  lintConfigImports,
  myIgnoresOnly,
  composedVariablesExclusives,
  variations,
  // libraries // v3
};

export default config;
