/* variants */

const EN = "en";
const ENGLISH = "English";

/* data */

const enData = Object.freeze({
  tsDoc: Object.freeze({
    core: Object.freeze({
      consts: Object.freeze({
        public: Object.freeze({
          successFalse:
            "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSFALSE` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSFALSE}`." /* variations: $COMMENT#TSDOC#CORE#CONSTS#PUBLIC#SUCCESSFALSE / core: $COMMENT#EN#TSDOC#CORE#CONSTS#PUBLIC#SUCCESSFALSE */,
          successTrue:
            "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSTRUE` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_TRUE` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSTRUE}`." /* variations: $COMMENT#TSDOC#CORE#CONSTS#PUBLIC#SUCCESSTRUE / core: $COMMENT#EN#TSDOC#CORE#CONSTS#PUBLIC#SUCCESSTRUE */,
          typeError:
            "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEERROR` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEERROR}`." /* variations: $COMMENT#TSDOC#CORE#CONSTS#PUBLIC#TYPEERROR / core: $COMMENT#EN#TSDOC#CORE#CONSTS#PUBLIC#TYPEERROR */,
          typeWarning:
            "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH  `...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEWARNING` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB, ...$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEWARNING}`." /* variations: $COMMENT#TSDOC#CORE#CONSTS#PUBLIC#TYPEWARNING / core: $COMMENT#EN#TSDOC#CORE#CONSTS#PUBLIC#TYPEWARNING */,
        }),
      }),
      defs: Object.freeze({
        public: Object.freeze({
          getSourceCode:
            "Gets the $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE from its absolute path." /* variations: $COMMENT#TSDOC#CORE#DEFS#PUBLIC#GETSOURCECODE / core: $COMMENT#EN#TSDOC#CORE#DEFS#PUBLIC#GETSOURCECODE */,
          makeSuccessFalseTypeError:
            "Makes a `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` object with a $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR of `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR}` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS." /* variations: $COMMENT#TSDOC#CORE#DEFS#PUBLIC#MAKESUCCESSFALSETYPEERROR / core: $COMMENT#EN#TSDOC#CORE#DEFS#PUBLIC#MAKESUCCESSFALSETYPEERROR */,
          makeSuccessFalseTypeWarning:
            "Makes a `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` object with a $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR of `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING}` $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS." /* variations: $COMMENT#TSDOC#CORE#DEFS#PUBLIC#MAKESUCCESSFALSETYPEWARNING / core: $COMMENT#EN#TSDOC#CORE#DEFS#PUBLIC#MAKESUCCESSFALSETYPEWARNING */,
        }),
      }),
      params: Object.freeze({
        public: Object.freeze({
          absolutePath:
            "The $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ABSOLUTEPATH $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ATHAND." /* variations: $COMMENT#TSDOC#CORE#PARAMS#PUBLIC#ABSOLUTEPATH / core: $COMMENT#EN#TSDOC#CORE#PARAMS#PUBLIC#ABSOLUTEPATH */,
          message:
            "The human-readable message of the $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ERROR." /* variations: $COMMENT#TSDOC#CORE#PARAMS#PUBLIC#MESSAGE / core: $COMMENT#EN#TSDOC#CORE#PARAMS#PUBLIC#MESSAGE */,
          status:
            "The static status text of the $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ERROR." /* variations: $COMMENT#TSDOC#CORE#PARAMS#PUBLIC#STATUS / core: $COMMENT#EN#TSDOC#CORE#PARAMS#PUBLIC#STATUS */,
        }),
      }),
      returns: Object.freeze({
        public: Object.freeze({
          getSourceCode:
            "The $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE, from which the AST (`sourceCode.ast`) and all comments (`sourceCode.getAllComments()`) can be extracted, inside a `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_TRUE}` object at its `sourceCode` key. In case of an error, a `{$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE}` object is returned instead." /* variations: $COMMENT#TSDOC#CORE#RETURNS#PUBLIC#GETSOURCECODE / core: $COMMENT#EN#TSDOC#CORE#RETURNS#PUBLIC#GETSOURCECODE */, // /!\ a recursive composed variable /!\
        }),
      }),
    }),
    tests: Object.freeze({
      defs: Object.freeze({
        assertFailureWithMessage:
          "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_ASSERTS that `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#GETSOURCECODE` fails $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#WHENITSHOULD." /* variations: $COMMENT#TSDOC#TESTS#DEFS#ASSERTFAILUREWITHMESSAGE / core: $COMMENT#EN#TSDOC#TESTS#DEFS#ASSERTFAILUREWITHMESSAGE */,
        assertSuccess:
          "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_ASSERTS that `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#GETSOURCECODE` succeeds $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#WHENITSHOULD." /* variations: $COMMENT#TSDOC#TESTS#DEFS#ASSERTSUCCESS / core: $COMMENT#EN#TSDOC#TESTS#DEFS#ASSERTSUCCESS */,
      }),
      params: Object.freeze({
        getSourceCodeResults:
          "The results of the `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#GETSOURCECODE` instance called in the test, whose success or failure is evaluated via its `$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS` key's boolean value." /* variations: $COMMENT#TSDOC#TESTS#PARAMS#GETSOURCECODERESULTS / core: $COMMENT#EN#TSDOC#TESTS#PARAMS#GETSOURCECODERESULTS */,
        expectedMessage:
          "The expected $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#MESSAGE of the error that should be encountered during failure, from which the $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#STATUS can be inferred." /* variations: $COMMENT#TSDOC#TESTS#PARAMS#EXPECTEDMESSAGE / core: $COMMENT#EN#TSDOC#TESTS#PARAMS#EXPECTEDMESSAGE */,
      }),
    }),
  }),
  composedVariablesExclusives: Object.freeze({
    // tsDoc.core.consts
    successFalse:
      "successFalse" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSFALSE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSFALSE */,
    successTrue:
      "successTrue" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSTRUE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSTRUE */,
    typeError:
      "typeError" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TYPEERROR / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEERROR */,
    typeWarning:
      "typeWarning" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TYPEWARNING / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEWARNING */,
    success_false:
      "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#FALSE" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE */,
    success_true:
      "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TRUE" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_TRUE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_TRUE */,
    type_error:
      "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ERROR" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR */,
    type_warning:
      "$COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#WARNING" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING */,
    success:
      "success" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS */,
    false:
      "false" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#FALSE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#FALSE */,
    true: "true" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TRUE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TRUE */,
    type: "type" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TYPE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE */,
    error:
      "error" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#ERROR / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ERROR */,
    warning:
      "warning" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#WARNING / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#WARNING */,
    _applyLastWith:
      "Apply last with" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH */ /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#APPLYLASTWITH / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH */,
    toEnsure:
      "to ensure that" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE */,
    sitsAtTopLike:
      "sits at the top of its object's type definition, like" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE */,
    propApropB:
      "propertyA, propertyB" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB */,
    // tsDoc.core.defs
    eslintSourceCode:
      "ESLint-generated `SourceCode` object of a file" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE */,
    singleError:
      "single error in its errors array" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#SINGLEERROR */,
    basedOnMessageAndStatus:
      "based on the message it is meant to display and the status it is meant to have" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#BASEDONMESSAGEANDSTATUS */,
    // tsDoc.core.params
    absolutePath:
      "absolute path of the file" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#ABSOLUTEPATH / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ABSOLUTEPATH */,
    atHand:
      "at hand" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#ATHAND / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#ATHAND */,
    // tsDoc.tests.defs
    _asserts:
      "Asserts" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#_ASSERTS / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#_ASSERTS */,
    getSourceCode:
      "getSourceCode" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#GETSOURCECODE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#GETSOURCECODE */,
    whenItShould:
      "when it should" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#WHENITSHOULD / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#WHENITSHOULD */,
    // tsDoc.tests.params
    message:
      "message" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#MESSAGE / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#MESSAGE */,
    status:
      "status" /* variations: $COMMENT#COMPOSEDVARIABLESEXCLUSIVES#STATUS / core: $COMMENT#EN#COMPOSEDVARIABLESEXCLUSIVES#STATUS */,
  }),
});

const data = Object.freeze({
  [EN]: enData,
});

/* ignores */

const ignores = [];

/* lintConfigImports */

const lintConfigImports = false; // can be omitted

/* myIgnoresOnly */

const myIgnoresOnly = false; // can be omitted

/* composedVariablesExclusives */

const enComposedVariablesExclusives = [
  "EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSFALSE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESSTRUE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEERROR",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#TYPEWARNING",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_FALSE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS_TRUE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_ERROR",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE_WARNING",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#SUCCESS",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#FALSE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#TRUE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#TYPE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#ERROR",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#WARNING",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#_APPLYLASTWITH",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#TOENSURE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#SITSATTOPLIKE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#PROPAPROPB",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#ESLINTSOURCECODE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#ABSOLUTEPATH",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#ATHAND",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#_ASSERTS",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#GETSOURCECODE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#WHENITSHOULD",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#MESSAGE",
  "EN#COMPOSEDVARIABLESEXCLUSIVES#STATUS",
];

const composedVariablesExclusives = [...enComposedVariablesExclusives]; // can be omitted, composed variables allowed

/* variations */

const variations = Object.freeze({
  // Defines all variants that have matching variations duly defined within the top-level keys of `data`.
  variants: Object.freeze({
    [EN]: Object.freeze({ label: ENGLISH }),
  }),
  // Defines the current variant that Comment Variables currently resolves to.
  variant: EN,
  // Defines the reference variation that all other variations need to have (or aim to have) matching keys with. Requires a JavaScript variable as it needs to be the exact same object as the one referenced at `data[variations.referenceVariant]`.
  referenceData: enData,
  // Defines the variant of the reference variation.
  referenceVariant: EN,
  // Defines the behavior of the error handling in case of variations that do not match one-to-one with the reference variation. If `true`, allows incomplete variations data to remain. If `false`, errors and guides the fixing of missing variations data.
  allowIncompleteVariations: true,
  // Defines which variants' `#PUBLIC#` Comment Variables should be publicly available, by default via `comments.public.mjs` and `comments.public.json`.
  // public: [EN] // NEW
});

const config = {
  data,
  ignores,
  lintConfigImports,
  myIgnoresOnly,
  composedVariablesExclusives,
  variations,
};

export default config;
