/* error statuses */

/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#STATUSES#CODE_NOT_STRING */
export const CODE_NOT_STRING = "CODE_NOT_STRING";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#STATUSES#ABSOLUTEPATH_NOT_STRING */
export const ABSOLUTEPATH_NOT_STRING = "ABSOLUTEPATH_NOT_STRING";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#STATUSES#ABSOLUTEPATH_NOT_ABSOLUTE */
export const ABSOLUTEPATH_NOT_ABSOLUTE = "ABSOLUTEPATH_NOT_ABSOLUTE";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#STATUSES#ABSOLUTE_PATH_NOT_FOUND */
export const ABSOLUTE_PATH_NOT_FOUND = "ABSOLUTE_PATH_NOT_FOUND";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#STATUSES#SOURCE_CODE_FATAL_SYNTAX */
export const SOURCE_CODE_FATAL_SYNTAX = "SOURCE_CODE_FATAL_SYNTAX";
