export const ABSOLUTE_PATH_NOT_STRING = "ABSOLUTE_PATH_NOT_STRING";
export const ABSOLUTE_PATH_NOT_FOUND = "ABSOLUTE_PATH_NOT_FOUND";
export const SOURCE_CODE_FATAL_SYNTAX = "SOURCE_CODE_FATAL_SYNTAX";
