export declare const CODE_NOT_STRING = "CODE_NOT_STRING";
export declare const ABSOLUTEPATH_NOT_STRING = "ABSOLUTEPATH_NOT_STRING";
export declare const ABSOLUTEPATH_NOT_ABSOLUTE = "ABSOLUTEPATH_NOT_ABSOLUTE";
export declare const ABSOLUTE_PATH_NOT_FOUND = "ABSOLUTE_PATH_NOT_FOUND";
export declare const SOURCE_CODE_FATAL_SYNTAX = "SOURCE_CODE_FATAL_SYNTAX";
